# f=open("Random.txt",'r')
# print(f.tell())
# f.seek(3)
# print(f.read())
# f.seek(6)
# print(f.read(5))
# print("curent location of pointer=",f.tell())
f=open("Random.txt",'rb')
print(f.tell())
f.seek(3)
print(f.read())
# f.seek(6,1)
f.seek(-6,1)
print(f.read(5))
print("curent location of pointer=",f.tell())